#Este archivo tiene prioridfad frente a la clase AppConfig.java
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 3s
    instances:
      products:
        base-config: defecto

spring:
   cloud:
      gateway:
        routes:
          - id: ms-product
            uri: lb://ms-product
            predicates:
              - Path=/productProject/api/products/**
              #- Header=token, \d+
              #- Header=token, 12345
              #- Method=GET, POST
              #- Query=color
              #- Cookie=color, azul
              #- Header=Content-Type, application/json
            filters:
              - name: CircuitBreaker
                args:
                  name: products
                  statusCodes: 500
                  fallbackUri: forward:/itemsProject/api/items/5
              - StripPrefix=1 #Se omite /productProject
              - name: EjemploCookie #ExampleCookie
                args:
                  message: Hola mi mensaje personalizado para producto
                  name: user
                  value: John
          - id: ms-items
            uri: lb://ms-items
            predicates:
              - Path=/itemsProject/api/items/**
            filters:
              - StripPrefix=1 #Se omite /itemsProject
              - AddRequestHeader=token-request, uno
              - AddResponseHeader=token-response, 1
              - AddRequestParameter=name, John
              - SetResponseHeader=Content-Type, application/xml
